const API = '/api/v1';
const state = { memories: [], results: [], selected: null, filters: { type: null, project: null }, view: 'library', layout: 'grid', query: '', searchTimer: null };
const $ = (selector) => document.querySelector(selector);
const elements = {
  grid: $('#memory-grid'), empty: $('#empty-state'), resultsLabel: $('#results-label'), search: $('#search-input'), mode: $('#search-mode'),
  detail: $('#detail-panel'), detailContent: $('#detail-content'), overlay: $('#overlay'), dialog: $('#memory-dialog'), form: $('#memory-form'),
  confirm: $('#confirm-dialog'), types: $('#type-filters'), projects: $('#project-filters'), filters: $('#active-filters'), sidebar: $('#sidebar')
};
const typeColors = { idea:'#d4a866', decision:'#c27b70', task:'#70a981', conversation:'#7196c9', document:'#9b82c5', person:'#ce8aa6', project:'#63aaa4', file:'#d18b62', memory:'#b3a57d' };

function escapeHtml(value='') { const node=document.createElement('div'); node.textContent=String(value); return node.innerHTML; }
function csv(value='') { return value.split(',').map(v=>v.trim()).filter(Boolean); }
function dateLabel(value) { if(!value) return 'agora'; const date=new Date(value), diff=Date.now()-date; const days=Math.floor(diff/86400000); if(days<=0)return 'hoje'; if(days===1)return 'ontem'; if(days<7)return `há ${days} dias`; return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(date); }
function fullDate(value) { return value ? new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : '—'; }
function renderMarkdown(value='') { let text=escapeHtml(value); text=text.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/^[-*] (.+)$/gm,'<li>$1</li>').replace(/(<li>.*<\/li>\n?)+/g,'<ul>$&</ul>').replace(/\n{2,}/g,'</p><p>').replace(/\n/g,'<br>'); return `<p>${text}</p>`; }
async function request(path, options={}) { const response=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); if(!response.ok){let message=`Erro ${response.status}`;try{const data=await response.json();message=data.detail||message}catch{}throw new Error(typeof message==='string'?message:JSON.stringify(message));} return response.status===204?null:response.json(); }
function toast(message,type='success'){const node=document.createElement('div');node.className=`toast ${type}`;node.textContent=message;$('#toast-region').append(node);setTimeout(()=>node.remove(),3600)}
function humanBytes(bytes=0){const units=['B','KB','MB','GB','TB'];let value=Number(bytes)||0,index=0;while(value>=1024&&index<units.length-1){value/=1024;index++}return `${value.toLocaleString('pt-BR',{maximumFractionDigits:index?1:0})} ${units[index]}`}
function humanUptime(seconds=0){const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60);return days?`${days}d ${hours}h`:hours?`${hours}h ${minutes}min`:`${minutes} min`}
async function loadSystem(){try{const d=await request(`${API}/system/status`);$('#sys-status').textContent=d.status==='ok'?'Tudo operacional':'Atenção necessária';$('#sys-host').textContent=`${d.hostname} · v${d.version}`;$('#sys-uptime').textContent=humanUptime(d.uptime_seconds);$('#sys-memories').textContent=d.memories;$('#sys-indexes').textContent=`${d.vector_count??'—'} vetores indexados`;$('#sys-files').textContent=d.files;$('#sys-markdown').textContent=`${d.markdown_files} documentos Markdown`;$('#sys-disk').textContent=`${d.storage.used_percent}% usado · ${humanBytes(d.storage.free_bytes)} livres`;$('#sys-disk-bar').style.width=`${Math.min(d.storage.used_percent,100)}%`;$('#sys-vault-size').textContent=`Vault ocupa ${humanBytes(d.storage.vault_bytes)} de ${humanBytes(d.storage.total_bytes)}`;$('#sys-backup').textContent=d.backup.available?fullDate(d.backup.created_at):'Backup automático ativo';$('#sys-backup-detail').textContent=d.backup.available?`${d.backup.filename} · ${humanBytes(d.backup.size_bytes)}`:'Detalhes protegidos pelo sistema.'}catch(error){toast(error.message,'error');$('#sys-status').textContent='Consulta indisponível'}}
function skeleton(){elements.grid.innerHTML=Array.from({length:6},()=>'<article class="memory-card skeleton"><span></span><span></span><span></span><span></span></article>').join('');elements.empty.classList.add('hidden')}

async function loadMemories({quiet=false}={}) {
  if(!quiet)skeleton();
  try {
    const params=new URLSearchParams({limit:'200'}); if(state.filters.type)params.set('type',state.filters.type); if(state.filters.project)params.set('project',state.filters.project);
    state.memories=await request(state.view==='files'?`${API}/files?limit=200`:`${API}/memories?${params}`); state.results=state.memories.map(memory=>({memory,score:null,score_breakdown:null}));
    if(state.view==='recent') state.results=state.results.slice().sort((a,b)=>new Date(b.memory.updated_at)-new Date(a.memory.updated_at)).slice(0,12);
    renderAll();
  } catch(error){elements.grid.innerHTML='';showEmpty('Não foi possível acessar o vault.');toast(error.message,'error')}
}
async function runSearch(){const query=elements.search.value.trim();state.query=query;if(!query)return loadMemories();skeleton();$('#view-title').textContent='Resultados da busca';$('#view-subtitle').textContent=`Explorando o vault por “${query}”.`;try{const params=new URLSearchParams({q:query,mode:elements.mode.value,limit:'60'});if(state.filters.type)params.set('type',state.filters.type);if(state.filters.project)params.set('project',state.filters.project);state.results=await request(`${API}/memories/search?${params}`);renderAll();}catch(error){elements.grid.innerHTML='';showEmpty('A busca não pôde ser concluída.');toast(error.message,'error')}}
function renderAll(){renderCards();renderFilters();renderStats();renderActiveFilters()}
function renderCards(){elements.grid.classList.toggle('list-layout',state.layout==='list');elements.grid.innerHTML='';const items=state.results;if(!items.length){showEmpty(state.query?'Tente outros termos ou remova os filtros.':state.view==='files'?'Envie o primeiro arquivo para iniciar sua biblioteca.':'Crie a primeira memória do seu vault para começar.');return}elements.empty.classList.add('hidden');elements.resultsLabel.textContent=`${items.length} ${items.length===1?'memória encontrada':'memórias encontradas'}`;items.forEach((item,index)=>{const m=item.memory||item,card=document.createElement('article');card.className='memory-card';card.style.setProperty('--type-color',typeColors[m.type]||typeColors.memory);card.style.animationDelay=`${Math.min(index,10)*25}ms`;const tags=(m.tags||[]).slice(0,2).map(tag=>`<span class="tag">#${escapeHtml(tag)}</span>`).join('');const more=(m.tags||[]).length>2?`<span class="more-tags">+${m.tags.length-2}</span>`:'';const score=item.score!=null?`<span class="score-pill">${Math.round(item.score*100)}%</span>`:'';card.innerHTML=`<div class="card-top"><span class="type-badge">${escapeHtml(m.type)}</span><span class="card-time">${dateLabel(m.updated_at)}</span></div><h3>${escapeHtml(m.title)}</h3><p class="card-summary">${escapeHtml(m.summary||m.content||'Sem descrição adicionada.')}</p><div class="card-footer">${tags}${more}${score}</div>`;card.addEventListener('click',()=>openDetail(item));elements.grid.append(card)})}
function showEmpty(message){elements.empty.classList.remove('hidden');$('#empty-message').textContent=message;elements.resultsLabel.textContent='0 memórias encontradas'}
function renderStats(){const all=state.memories;if(state.view!=='files')$('#all-count').textContent=all.length;$('#file-count').textContent=state.view==='files'?all.length:all.filter(m=>m.type==='file').length;$('#stat-memories').textContent=all.length;$('#stat-projects').textContent=new Set(all.map(m=>m.project).filter(Boolean)).size;$('#stat-types').textContent=new Set(all.map(m=>m.type)).size;$('#active-mode').textContent=state.query?elements.mode.value.toUpperCase():'VAULT'}
function tally(key){return state.memories.reduce((acc,m)=>{const value=m[key];if(value)acc[value]=(acc[value]||0)+1;return acc},{})}
function renderFilters(){const types=tally('type'),projects=tally('project');elements.types.innerHTML=Object.entries(types).sort().map(([name,count])=>filterButton('type',name,count)).join('');elements.projects.innerHTML=Object.entries(projects).sort().map(([name,count])=>filterButton('project',name,count)).join('');document.querySelectorAll('.filter-item').forEach(button=>button.addEventListener('click',()=>setFilter(button.dataset.key,button.dataset.value)))}
function filterButton(key,name,count){const active=state.filters[key]===name?' active':'';return `<button class="filter-item${active}" data-key="${key}" data-value="${escapeHtml(name)}"><i class="filter-dot" style="background:${key==='type'?(typeColors[name]||typeColors.memory):'#777'}"></i><span>${escapeHtml(name)}</span><span>${count}</span></button>`}
function setFilter(key,value){state.filters[key]=state.filters[key]===value?null:value;state.query?runSearch():loadMemories({quiet:true})}
function renderActiveFilters(){elements.filters.innerHTML=Object.entries(state.filters).filter(([,v])=>v).map(([k,v])=>`<span class="filter-chip">${k}: ${escapeHtml(v)}</span>`).join('')}

function openDetail(item){const m=item.memory||item;state.selected=m;const breakdown=item.score_breakdown,fileMeta=m.type==='file'?`<div><small>Formato</small><span>${escapeHtml(m.context?.mime_type||'—')}</span></div><div><small>Tamanho</small><span>${Number(m.context?.size_bytes||0).toLocaleString('pt-BR')} bytes</span></div><div><small>SHA-256</small><span title="${escapeHtml(m.context?.sha256||'')}">${escapeHtml((m.context?.sha256||'—').slice(0,16))}…</span></div><div><small>Nome original</small><span>${escapeHtml(m.context?.original_filename||m.title)}</span></div>`:'';elements.detailContent.innerHTML=`<div class="detail-body"><span class="detail-type">${escapeHtml(m.type)}</span><h2>${escapeHtml(m.title)}</h2><p class="detail-summary">${escapeHtml(m.summary||'Sem resumo.')}</p><div class="detail-meta"><div><small>Projeto</small><span>${escapeHtml(m.project||'—')}</span></div><div><small>Criada em</small><span>${fullDate(m.created_at)}</span></div><div><small>Fonte</small><span>${escapeHtml(m.context?.source||'—')}</span></div><div><small>Atualizada</small><span>${fullDate(m.updated_at)}</span></div>${fileMeta}${item.score!=null?`<div><small>Score final</small><span>${Math.round(item.score*100)}%</span></div><div><small>Semântica / Texto</small><span>${Math.round((breakdown?.semantic||0)*100)}% / ${Math.round((breakdown?.text||0)*100)}%</span></div>`:''}</div><div class="detail-tags">${(m.tags||[]).map(tag=>`<span class="tag">#${escapeHtml(tag)}</span>`).join('')}</div><div class="markdown">${renderMarkdown(m.content||'Sem conteúdo em Markdown.')}</div><div class="detail-actions">${m.type==='file'?`<a class="secondary-button" href="${API}/files/${encodeURIComponent(m.id)}/download">Baixar arquivo</a>`:`<button class="secondary-button" id="edit-detail">Editar</button>`}<button class="ghost-button danger-link" id="delete-detail">Excluir</button></div></div>`;elements.detail.classList.add('open');elements.detail.setAttribute('aria-hidden','false');elements.overlay.classList.add('visible');if(m.type!=='file')$('#edit-detail').addEventListener('click',()=>openForm(m));$('#delete-detail').addEventListener('click',()=>elements.confirm.showModal())}
function closeDetail(){elements.detail.classList.remove('open');elements.detail.setAttribute('aria-hidden','true');elements.overlay.classList.remove('visible')}
function openForm(memory=null){closeDetail();$('#memory-id').value=memory?.id||'';$('#form-eyebrow').textContent=memory?'ATUALIZAR ENTRADA':'NOVA ENTRADA';$('#form-title').textContent=memory?'Editar memória':'Criar memória';$('#field-title').value=memory?.title||'';$('#field-type').value=memory?.type||'memory';$('#field-project').value=memory?.project||'';$('#field-summary').value=memory?.summary||'';$('#field-content').value=memory?.content||'';$('#field-tags').value=(memory?.tags||[]).join(', ');$('#field-source').value=memory?.context?.source||'web';$('#field-language').value=memory?.context?.language||'pt-BR';elements.dialog.showModal();setTimeout(()=>$('#field-title').focus(),50)}
async function saveMemory(event){event.preventDefault();const id=$('#memory-id').value;const existing=state.memories.find(memory=>memory.id===id);const payload={title:$('#field-title').value.trim(),type:$('#field-type').value.trim()||'memory',project:$('#field-project').value.trim()||null,summary:$('#field-summary').value.trim()||null,content:$('#field-content').value,tags:csv($('#field-tags').value),context:{...(existing?.context||{}),source:$('#field-source').value.trim()||'web',language:$('#field-language').value.trim()||'pt-BR'}};if(id)delete payload.type;const button=$('#save-memory'),label=button.textContent;button.disabled=true;button.textContent='Salvando…';try{await request(id?`${API}/memories/${id}`:`${API}/memories`,{method:id?'PUT':'POST',body:JSON.stringify(payload)});elements.dialog.close();toast(id?'Memória atualizada.':'Memória guardada no vault.');state.query?await runSearch():await loadMemories({quiet:true})}catch(error){toast(error.message,'error')}finally{button.disabled=false;button.textContent=label}}
async function deleteMemory(){if(!state.selected)return;const button=$('#confirm-delete');button.disabled=true;try{const endpoint=state.selected.type==='file'?`${API}/files/${state.selected.id}`:`${API}/memories/${state.selected.id}`;await request(endpoint,{method:'DELETE'});elements.confirm.close();closeDetail();toast(state.selected.type==='file'?'Arquivo excluído.':'Memória excluída.');state.selected=null;state.query?await runSearch():await loadMemories({quiet:true})}catch(error){toast(error.message,'error')}finally{button.disabled=false}}

async function uploadFile(file){if(!file)return;const button=$('#upload-file'),label=button.textContent,resumeKey=`arkan-upload:${file.name}:${file.size}:${file.lastModified}`;button.disabled=true;try{let session=null,uploadId=localStorage.getItem(resumeKey);if(uploadId){try{session=await request(`${API}/files/uploads/${uploadId}`)}catch{localStorage.removeItem(resumeKey);uploadId=null}}if(!session){session=await request(`${API}/files/uploads`,{method:'POST',body:JSON.stringify({filename:file.name,size_bytes:file.size,content_type:file.type||'application/octet-stream',project:state.filters.project||null})});uploadId=session.upload_id;localStorage.setItem(resumeKey,uploadId)}let offset=session.received_bytes,chunkSize=session.chunk_size;while(offset<file.size){button.textContent=`Enviando ${Math.floor(offset/file.size*100)}%`;const chunk=file.slice(offset,Math.min(offset+chunkSize,file.size)),response=await fetch(`${API}/files/uploads/${uploadId}`,{method:'PUT',headers:{'Content-Type':'application/octet-stream','Upload-Offset':String(offset)},body:chunk});if(!response.ok){let message=`Erro ${response.status}`;try{message=(await response.json()).detail||message}catch{}throw new Error(message)}session=await response.json();offset=session.received_bytes}button.textContent='Finalizando…';const result=await request(`${API}/files/uploads/${uploadId}/complete`,{method:'POST',body:'{}'});localStorage.removeItem(resumeKey);toast(result.deduplicated?'Arquivo já existia; entrada reutilizada.':'Arquivo guardado e indexado no vault.');state.view='files';state.query='';elements.search.value='';document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view==='files'));window.ArkanGraph?.hide();$('#view-title').textContent='Biblioteca de arquivos';$('#view-subtitle').textContent='Originais preservados, verificados por hash e prontos para download.';await loadMemories({quiet:true})}catch(error){toast(`${error.message} Você pode selecionar o mesmo arquivo para continuar.`,'error')}finally{button.disabled=false;button.textContent=label;$('#file-input').value=''}}

function bind(){
  $('#upload-file').addEventListener('click',()=>$('#file-input').click());$('#file-input').addEventListener('change',event=>uploadFile(event.target.files?.[0]));
  $('#new-memory').addEventListener('click',()=>openForm());$('#empty-create').addEventListener('click',()=>openForm());$('#close-form').addEventListener('click',()=>elements.dialog.close());$('#cancel-form').addEventListener('click',()=>elements.dialog.close());elements.form.addEventListener('submit',saveMemory);
  $('#close-detail').addEventListener('click',closeDetail);elements.overlay.addEventListener('click',()=>{closeDetail();elements.sidebar.classList.remove('open')});$('#cancel-delete').addEventListener('click',()=>elements.confirm.close());$('#confirm-delete').addEventListener('click',deleteMemory);
  elements.search.addEventListener('input',()=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(runSearch,450)});elements.mode.addEventListener('change',()=>state.query&&runSearch());$('#refresh-button').addEventListener('click',()=>state.query?runSearch():loadMemories());
  $('#clear-filters').addEventListener('click',()=>{state.filters={type:null,project:null};state.query?runSearch():loadMemories({quiet:true})});$('#menu-button').addEventListener('click',()=>{elements.sidebar.classList.add('open');elements.overlay.classList.add('visible')});
  document.querySelectorAll('.view-toggle').forEach(button=>button.addEventListener('click',()=>{state.layout=button.dataset.layout;document.querySelectorAll('.view-toggle').forEach(b=>b.classList.toggle('active',b===button));renderCards()}));
  document.querySelectorAll('.nav-item').forEach(button=>button.addEventListener('click',()=>{state.view=button.dataset.view;state.query='';elements.search.value='';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b===button));if(state.view==='graph'){$('#system-view').classList.add('hidden');window.ArkanGraph.show();return}window.ArkanGraph?.hide();if(state.view==='system'){$('#system-view').classList.remove('hidden');$('.page-heading').classList.add('hidden');$('#stats-strip').classList.add('hidden');$('.results-meta').classList.add('hidden');elements.grid.classList.add('hidden');elements.empty.classList.add('hidden');loadSystem();return}$('#system-view').classList.add('hidden');$('.page-heading').classList.remove('hidden');$('#stats-strip').classList.remove('hidden');$('.results-meta').classList.remove('hidden');elements.grid.classList.remove('hidden');$('#view-title').textContent=state.view==='recent'?'Memórias recentes':state.view==='files'?'Biblioteca de arquivos':'Sua biblioteca';$('#view-subtitle').textContent=state.view==='files'?'Originais preservados, verificados por hash e prontos para download.':'Tudo que seus agentes precisam lembrar, organizado em um só lugar.';loadMemories({quiet:true})}));
  $('#system-refresh').addEventListener('click',loadSystem);
  document.addEventListener('keydown',event=>{if(event.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){event.preventDefault();elements.search.focus()}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='n'){event.preventDefault();openForm()}if(event.key==='Escape')closeDetail()});
}
async function boot(){bind();try{const health=await request('/health');$('#health-label').textContent=`v${health.version} · conectado`}catch{$('#health-label').textContent='API indisponível';$('.status-dot').style.background='var(--red)'}await loadMemories()}
window.addEventListener('DOMContentLoaded',boot);
